# Generated by Django 5.0.7 on 2024-08-09 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_userdetail_user_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_details',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user_details',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user_details',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AlterField(
            model_name='user_details',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
    ]
