# Generated by Django 5.0.7 on 2024-08-10 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_user_details_is_active_user_details_is_admin_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user_details',
            table='user_details',
        ),
    ]
