# Generated by Django 5.0.7 on 2024-08-10 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_user_details_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user_details',
            options={'verbose_name': 'User Details', 'verbose_name_plural': 'User Details'},
        ),
    ]
